<?php
/**
 * Plugin Name: Hayat Tayyiba Health Score
 * Description: A 60-Second Health Assessment tool built with React.
 * Version: 1.0.0
 * Author: RND Experts
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

class Hayat_Health_Score {
    public function __construct() {
        register_activation_hook( __FILE__, [ $this, 'activate_plugin' ] );
        add_shortcode( 'hayat_health_score', [ $this, 'render_shortcode' ] );
        add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_scripts' ] );
        add_action( 'rest_api_init', [ $this, 'register_rest_routes' ] );
    }

    public function activate_plugin() {
        global $wpdb;
        $table_name = $wpdb->prefix . 'hayat_assessments';
        $charset_collate = $wpdb->get_charset_collate();

        $sql = "CREATE TABLE $table_name (
            id bigint(20) NOT NULL AUTO_INCREMENT,
            user_id bigint(20) NULL,
            first_name varchar(100) NULL,
            email varchar(100) NULL,
            phone varchar(50) NULL,
            risk_score int(11) NULL,
            health_score int(11) NULL,
            readiness_score int(11) NULL,
            top_opportunities text NULL,
            raw_answers longtext NULL,
            utm_source varchar(100) NULL,
            created_at datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY  (id)
        ) $charset_collate;";

        require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
        dbDelta( $sql );
    }

    public function register_rest_routes() {
        register_rest_route( 'hayat/v1', '/submit', [
            'methods'  => 'POST',
            'callback' => [ $this, 'handle_submission' ],
            'permission_callback' => '__return_true', // Public endpoint
        ] );
    }

    public function handle_submission( $request ) {
        global $wpdb;
        $table_name = $wpdb->prefix . 'hayat_assessments';
        
        $params = $request->get_json_params();

        // For now, we are just saving raw answers (Tracer bullet)
        $wpdb->insert(
            $table_name,
            [
                'raw_answers' => wp_json_encode( $params ),
                'created_at'  => current_time( 'mysql' )
            ]
        );

        if ( $wpdb->insert_id ) {
            return rest_ensure_response( [
                'success' => true,
                'message' => 'Assessment saved successfully',
                'id'      => $wpdb->insert_id
            ] );
        }

        return new WP_Error( 'db_error', 'Could not save assessment', [ 'status' => 500 ] );
    }

    public function render_shortcode() {
        // Output the container div for React to mount into
        return '<div id="hayat-health-score-root"></div>';
    }

    public function enqueue_scripts() {
        // Ensure scripts only load on pages containing the shortcode
        global $post;
        if ( is_a( $post, 'WP_Post' ) && has_shortcode( $post->post_content, 'hayat_health_score' ) ) {
            
            // Load dependencies generated by wp-scripts
            $asset_file_path = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
            if ( file_exists( $asset_file_path ) ) {
                $asset_file = include( $asset_file_path );
                wp_enqueue_script(
                    'hayat-health-score-js',
                    plugin_dir_url( __FILE__ ) . 'build/index.js',
                    $asset_file['dependencies'],
                    $asset_file['version'],
                    true
                );
            }

            // Pass REST API URL and Nonce to the React app
            wp_localize_script( 'hayat-health-score-js', 'hayatHealthData', [
                'restUrl' => esc_url_raw( rest_url( 'hayat/v1/submit' ) ),
                'nonce'   => wp_create_nonce( 'wp_rest' )
            ] );
        }
    }
}

// Initialize the plugin
new Hayat_Health_Score();
