<?php
/**
 * Plugin Name: Hayat Tayyiba Health Score
 * Description: A 60-Second Health Assessment tool built with React.
 * Version: 1.0.0
 * Author: RND Experts
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Load Composer autoloader if it exists
if ( file_exists( plugin_dir_path( __FILE__ ) . 'vendor/autoload.php' ) ) {
    require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';
}

require_once plugin_dir_path( __FILE__ ) . 'includes/class-hayat-api.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/class-hayat-pdf.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/class-hayat-email.php';
require_once plugin_dir_path( __FILE__ ) . 'includes/class-hayat-admin.php';

class Hayat_Health_Score {
    public function __construct() {
        register_activation_hook( __FILE__, [ $this, 'activate_plugin' ] );
        add_shortcode( 'hayat_health_score', [ $this, 'render_shortcode' ] );
        add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_scripts' ] );
        
        // Register async hook for email and PDF processing
        add_action( 'hayat_process_assessment', [ 'Hayat_Health_Score_Email', 'process_assessment_and_email' ] );
        
        new Hayat_Health_Score_API();

        if ( is_admin() ) {
            new Hayat_Health_Score_Admin();
        }
    }

    public function activate_plugin() {
        global $wpdb;
        $table_name = $wpdb->prefix . 'hayat_assessments';
        $charset_collate = $wpdb->get_charset_collate();

        $sql = "CREATE TABLE $table_name (
            id bigint(20) NOT NULL AUTO_INCREMENT,
            user_id bigint(20) NULL,
            first_name varchar(100) NULL,
            email varchar(100) NULL,
            phone varchar(50) NULL,
            risk_score int(11) NULL,
            health_score int(11) NULL,
            readiness_score int(11) NULL,
            top_opportunities text NULL,
            raw_answers longtext NULL,
            utm_source varchar(100) NULL,
            status varchar(50) DEFAULT 'Needs Follow-up' NULL,
            created_at datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY  (id)
        ) $charset_collate;";

        require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
        dbDelta( $sql );
    }

    public function render_shortcode() {
        // Output the container div for React to mount into
        return '<div id="hayat-health-score-root"></div>';
    }

    public function enqueue_scripts() {
        // Ensure scripts only load on pages containing the shortcode
        global $post;
        if ( is_a( $post, 'WP_Post' ) && has_shortcode( $post->post_content, 'hayat_health_score' ) ) {
            
            // Load dependencies generated by wp-scripts
            $asset_file_path = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';
            if ( file_exists( $asset_file_path ) ) {
                $asset_file = include( $asset_file_path );
                wp_enqueue_script(
                    'hayat-health-score-js',
                    plugin_dir_url( __FILE__ ) . 'build/index.js',
                    $asset_file['dependencies'],
                    $asset_file['version'],
                    true
                );
            }

            // Pass REST API URL, Nonce, and Booking URL to the React app
            $booking_url = get_option( 'hayat_booking_url', 'https://cal.com/hayattayyiba/assessment' );
            $primary_color = get_option( 'hayat_primary_color', '#2E8B57' );
            wp_localize_script( 'hayat-health-score-js', 'hayatHealthData', [
                'restUrl'    => esc_url_raw( rest_url( 'hayat/v1/submit' ) ),
                'nonce'      => wp_create_nonce( 'wp_rest' ),
                'bookingUrl' => esc_url_raw( $booking_url ),
                'primaryColor' => sanitize_hex_color( $primary_color )
            ] );
            
            wp_enqueue_style(
                'hayat-health-score-custom-css',
                plugin_dir_url( __FILE__ ) . 'assets/css/custom.css',
                [],
                '1.0.0'
            );
        }
    }
}

// Initialize the plugin
new Hayat_Health_Score();
